apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runright.fullname" . }}
  labels:
    {{- include "runright.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ include "runright.dsn" . | quote }}
  {{- if .Values.config.apiKey }}
  api-key: {{ .Values.config.apiKey | quote }}
  {{- else if .Values.existingSecret }}
  {{- /* user is managing the secret themselves — no-op */}}
  {{- end }}
