apiVersion: 1

datasources:
  - name: RunRight
    type: postgres
    url: localhost:5435
    user: runright
    secureJsonData:
      password: runright
    jsonData:
      database: runright
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
